name: C Code Validation

on:
  push:
    branches:
      - main  # Adjust to your main branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Compile C code and capture errors
      run: |
        error_flag=0
        for file in $(find . -name "*.c"); do
          gcc -o /dev/null "$file" 2>&1 | tee error.log
          if [ $? -ne 0 ]; then
            echo "Error in file: $file"
            cat error.log
            error_flag=1
          fi
        done
        if [ $error_flag -eq 0 ]; then
          echo "C code is valid."
        else
          exit 1
        fi
