name: Generate files.log

on:
  push:
    branches:
      - main  # Adjust to your main branch

jobs:
  generate-files-log:
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Generate files.log
      run: |
        find . > files.log
        echo "File structure saved in files.log"
      
    - name: Upload files.log
      uses: actions/upload-artifact@v2
      with:
        name: files-log
        path: files.log
